#!/usr/bin/env python3
"""Generate the Codex skill mirror from the Claude command tree.

`.claude/commands/` is the single source of truth. `.agents/skills/` is a
build output — never edit it by hand.

The two trees were previously maintained as byte-identical hand copies with
no generator and no check, which is a fork that has not diverged *yet*. The
mirror also carried names like `source-command-gm-mode` and descriptions
reading "Migrated source command `gm-mode`", so Codex had no more routing
signal than Claude did before the descriptions landed.

Run `--check` in CI to assert the mirror is in sync.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
COMMANDS = ROOT / ".claude" / "commands"
SKILLS = ROOT / ".agents" / "skills"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.S)
FIELD_RE = re.compile(r'^([a-z][\w-]*):\s*(.*)$', re.M)

GENERATED_HEADER = "<!-- Generated by scripts/sync_skills.py from {source}. Do not edit. -->"


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Return (fields, body). Raises if the file has no frontmatter."""
    m = FRONTMATTER_RE.match(text)
    if not m:
        raise ValueError("no YAML frontmatter")
    fields = {}
    for key, raw in FIELD_RE.findall(m.group(1)):
        value = raw.strip()
        if len(value) >= 2 and value[0] == value[-1] == '"':
            value = value[1:-1].replace('\\"', '"')
        fields[key] = value
    return fields, text[m.end():]


def iter_commands():
    """Yield (slug, category, path) for every command, categorized or not."""
    for path in sorted(COMMANDS.rglob("*.md")):
        rel = path.relative_to(COMMANDS)
        category = rel.parts[0] if len(rel.parts) > 1 else ""
        slug = f"{category}-{path.stem}" if category else path.stem
        yield slug, category, path


def render(slug: str, category: str, path: pathlib.Path) -> str:
    fields, body = parse_frontmatter(path.read_text())
    description = fields.get("description", "").strip()
    if not description:
        raise ValueError("empty description")
    # Codex reads name/description the same way Claude does; the invocation
    # differs (`/trades:find` vs the skill name), so state it in the body
    # rather than inventing a second description.
    header = GENERATED_HEADER.format(source=path.relative_to(ROOT))
    invocation = f"/{category}:{path.stem}" if category else f"/{path.stem}"
    return (
        "---\n"
        f'name: "{slug}"\n'
        f'description: "{description.replace(chr(34), chr(92) + chr(34))}"\n'
        "---\n\n"
        f"{header}\n\n"
        f"In Claude Code this skill is `{invocation}`.\n\n"
        f"{body.lstrip()}"
    )


def build() -> dict[str, str]:
    out = {}
    for slug, category, path in iter_commands():
        try:
            out[slug] = render(slug, category, path)
        except ValueError as e:
            print(f"error: {path.relative_to(ROOT)}: {e}", file=sys.stderr)
            raise SystemExit(1)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the mirror is out of date; write nothing")
    args = ap.parse_args()

    want = build()

    if args.check:
        have = {p.parent.name: p.read_text() for p in SKILLS.glob("*/SKILL.md")}
        stale = sorted(set(have) - set(want))
        missing = sorted(set(want) - set(have))
        changed = sorted(s for s in set(want) & set(have) if want[s] != have[s])
        if stale or missing or changed:
            for s in missing:
                print(f"missing:  {s}")
            for s in stale:
                print(f"orphaned: {s}")
            for s in changed:
                print(f"stale:    {s}")
            print("\n.agents/skills is out of date. Run: python3 scripts/sync_skills.py",
                  file=sys.stderr)
            return 1
        print(f"in sync: {len(want)} skills")
        return 0

    if SKILLS.exists():
        shutil.rmtree(SKILLS)
    for slug, text in want.items():
        target = SKILLS / slug / "SKILL.md"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text)
    print(f"wrote {len(want)} skills to {SKILLS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
